assets_dir = "/usr/share/ludo/assets"
audio_volume = 0.5
bluetooth_service = false
cores_dir = "/usr/share/ludo/cores"
database_dir = "/usr/share/ludo/database"
files_dir = "/home/polymath"
input_map_axis_to_dpad = false
menu_audio_volume = 0.25
menu_showhiddenfiles = false
playlists_dir = "/home/polymath/.local/share/ludo/playlists"
samba_service = false
savefiles_dir = "/home/polymath/.local/share/ludo/savefiles"
savestates_dir = "/home/polymath/.local/share/ludo/savestates"
screenshots_dir = "/home/polymath/.local/share/ludo/screenshots"
ssh_service = false
system_dir = "/home/polymath/.local/share/ludo/system"
thumbnail_dir = "/home/polymath/.local/share/ludo/thumbnails"
video_dark_mode = false
video_filter = "Pixel Perfect"
video_fullscreen = false
video_monitor_index = 0

[core_for_playlist]
  "Atari - 2600" = "stella2014_libretro"
  "Atari - 5200" = "atari800_libretro"
  "Atari - 7800" = "prosystem_libretro"
  "Atari - Jaguar" = "virtualjaguar_libretro"
  "Atari - Lynx" = "handy_libretro"
  "Atari - ST" = "hatari_libretro"
  "Bandai - WonderSwan" = "mednafen_wswan_libretro"
  "Bandai - WonderSwan Color" = "mednafen_wswan_libretro"
  "Cave Story" = "nxengine_libretro"
  ChaiLove = "chailove_libretro"
  "Coleco - ColecoVision" = "bluemsx_libretro"
  "FBNeo - Arcade Games" = "fbneo_libretro"
  "GCE - Vectrex" = "vecx_libretro"
  "Magnavox - Odyssey2" = "o2em_libretro"
  "Microsoft - MSX" = "bluemsx_libretro"
  "Microsoft - MSX2" = "bluemsx_libretro"
  "NEC - PC Engine - TurboGrafx 16" = "mednafen_pce_libretro"
  "NEC - PC Engine CD - TurboGrafx-CD" = "mednafen_pce_libretro"
  "NEC - PC Engine SuperGrafx" = "mednafen_pce_libretro"
  "NEC - PC-FX" = "mednafen_pcfx_libretro"
  "Nintendo - Family Computer Disk System" = "fceumm_libretro"
  "Nintendo - Game Boy" = "gambatte_libretro"
  "Nintendo - Game Boy Advance" = "mgba_libretro"
  "Nintendo - Game Boy Color" = "gambatte_libretro"
  "Nintendo - Nintendo 64" = "mupen64plus_next_libretro"
  "Nintendo - Nintendo DS" = "melonds_libretro"
  "Nintendo - Nintendo Entertainment System" = "fceumm_libretro"
  "Nintendo - Pokemon Mini" = "pokemini_libretro"
  "Nintendo - Super Nintendo Entertainment System" = "snes9x_libretro"
  "Nintendo - Virtual Boy" = "mednafen_vb_libretro"
  "SNK - Neo Geo Pocket" = "mednafen_ngp_libretro"
  "SNK - Neo Geo Pocket Color" = "mednafen_ngp_libretro"
  "Sega - 32X" = "picodrive_libretro"
  "Sega - Game Gear" = "genesis_plus_gx_libretro"
  "Sega - Master System - Mark III" = "genesis_plus_gx_libretro"
  "Sega - Mega Drive - Genesis" = "genesis_plus_gx_libretro"
  "Sega - Mega-CD - Sega CD" = "genesis_plus_gx_libretro"
  "Sega - PICO" = "picodrive_libretro"
  "Sega - SG-1000" = "genesis_plus_gx_libretro"
  "Sega - Saturn" = "mednafen_saturn_libretro"
  "Sony - PlayStation" = "swanstation_libretro"
